### ISSUE TITLE
CORS Issues

### ISSUE THREAD

**Issue by qooplmao** [SCDesigns/jet-log-client#1]
Hi,

I was going to give your app a play but it seems you haven't get your server set up to allow CORS so every attempt to contact the API throws an error.

![image](https://user-images.githubusercontent.com/2874965/31042992-cdb77840-a579-11e7-9ce5-7550fecb7e67.png)

**Comment by SCDesigns** [comment]
I appreciate the feedback I'll look into it and get back to you shortly.
